apiVersion: v1
kind:    Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.ioname: ingress-nginx
    app.kubernetes.iopart-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.ioname: ingress-nginx
    app.kubernetes.iopart-of: ingress-nginx
---
